name: Build TA-Lib wheels for Windows and macOS

on:
  workflow_dispatch:

env:
  TALIB_C_VER: 0.6.4
  TALIB_PY_VER: 0.6.3
  PIP_NO_VERIFY: 0
  PIP_VERBOSE: 1
  CIBW_BUILD_VERBOSITY: 2
  CIBW_BEFORE_BUILD: pip install -U setuptools wheel numpy Cython
  CIBW_TEST_SKIP: "*"
  CIBW_SKIP: "pp* cp36* cp37* cp39* cp310* cp311*"
  MSBUILDTREATHIGHERTOOLSVERSIONASCURRENT: 1

jobs:
  build_win_amd64_py312:
    name: Build Windows AMD64 wheels (Python 3.12)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: build.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ENVIRONMENT_WINDOWS: >
            TA_LIBRARY_PATH="ta-lib-$TALIB_C_VER\\_build;$LIB"
            TA_INCLUDE_PATH="ta-lib-$TALIB_C_VER\\include;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-win-amd64-py312

  build_win_x86_py312:
    name: Build Windows x86 wheels (Python 3.12)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - run: build.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: x86
          CIBW_ENVIRONMENT_WINDOWS: >
            TA_LIBRARY_PATH="ta-lib-$TALIB_C_VER\\_build;$LIB"
            TA_INCLUDE_PATH="ta-lib-$TALIB_C_VER\\include;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-win-x86-py312

  build_macos_arm64_py38:
    name: Build macOS ARM64 wheels (Python 3.8)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install TA-Lib C library
        run: |
          wget https://github.com/TA-Lib/ta-lib/releases/download/v$TALIB_C_VER/ta-lib-$TALIB_C_VER-src.tar.gz
          tar -xzf ta-lib-$TALIB_C_VER-src.tar.gz
          cd ta-lib-$TALIB_C_VER
          ./configure --prefix=/usr/local
          make
          sudo make install
        env:
          MACOSX_DEPLOYMENT_TARGET: "15.0"
      - name: Download TA-Lib Python source
        run: |
          wget https://github.com/TA-Lib/ta-lib-python/archive/refs/tags/TA_Lib-$TALIB_PY_VER.tar.gz
          tar -xzf TA_Lib-$TALIB_PY_VER.tar.gz
          mv ta-lib-python-TA_Lib-$TALIB_PY_VER talib-python
      - uses: pypa/cibuildwheel@v2.22.0
        with:
          package-dir: ./talib-python
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_BUILD: "cp38-*"
          CIBW_BEFORE_BUILD: pip install -U setuptools wheel "numpy<2" Cython
          CIBW_ENVIRONMENT_MACOS: >
            TA_LIBRARY_PATH="/usr/local/lib"
            TA_INCLUDE_PATH="/usr/local/include"
            MACOSX_DEPLOYMENT_TARGET="15.0"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-macos-arm64-py38

  build_macos_arm64_py312:
    name: Build macOS ARM64 wheels (Python 3.12)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install TA-Lib C library
        run: |
          wget https://github.com/TA-Lib/ta-lib/releases/download/v$TALIB_C_VER/ta-lib-$TALIB_C_VER-src.tar.gz
          tar -xzf ta-lib-$TALIB_C_VER-src.tar.gz
          cd ta-lib-$TALIB_C_VER
          ./configure --prefix=/usr/local
          make
          sudo make install
        env:
          MACOSX_DEPLOYMENT_TARGET: "15.0"
      - name: Download TA-Lib Python source
        run: |
          wget https://github.com/TA-Lib/ta-lib-python/archive/refs/tags/TA_Lib-$TALIB_PY_VER.tar.gz
          tar -xzf TA_Lib-$TALIB_PY_VER.tar.gz
          mv ta-lib-python-TA_Lib-$TALIB_PY_VER talib-python
      - uses: pypa/cibuildwheel@v2.22.0
        with:
          package-dir: ./talib-python
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_BUILD: "cp312-*"
          CIBW_BEFORE_BUILD: pip install -U setuptools wheel "numpy<2" Cython
          CIBW_ENVIRONMENT_MACOS: >
            TA_LIBRARY_PATH="/usr/local/lib"
            TA_INCLUDE_PATH="/usr/local/include"
            MACOSX_DEPLOYMENT_TARGET="15.0"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-macos-arm64-py312
